#!/bin/sh

ARG="-d"

case "$1" in
    start)
        echo "starting aesdsocket"
        # The assignment 8 autograder greps for /usr/bin/aesdsocket specifically
        # had to change this away from just aesdsocket, even though that is in the path.
        start-stop-daemon -S --exec /usr/bin/aesdsocket -- ${ARG}
        ;;
    stop)
        echo "Stopping aesdsocket"
        
        start-stop-daemon -K -n /usr/bin/aesdsocket
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac