#!/bin/sh

ARG="-d"

case "$1" in
    start)
        echo "starting aesdsocket"
        start-stop-daemon -S --exec aesdsocket -- ${ARG}
        ;;
    stop)
        echo "Stopping aesdsocket"
        start-stop-daemon -K -n aesdsocket
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac